server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sleeve?characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: 11111111
  jpa:
    show_sql: true
    hibernate:
      ddl-auto: none
      format_sql: true