
imissyou:
  api-package: com.lin.imissyou.api
  year-codes: A,B,C,D,E,F,G,H,I,J,K,L

spring:
  profiles:
    active: dev
  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.MySQLDialect
  jackson:
    property-naming-strategy: SNAKE_CASE
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: true

wx:
  appid: wx10822e546c7f50c9
  appsecret: 54ff28f3c822aa005475919c3d2d9222
  code2session: https://api.weixin.qq.com/sns/jscode2session?appid={0}&secret={1}&js_code={2}&grant_type=authorization_code